### ISSUE TITLE
Allow modification of state value

### ISSUE THREAD

**Issue by mattbaker** [mattbaker/Reactive.js#9]
Modifying a state value is currently awkward and inefficient:

```javascript
var x = $R.state(1);
//Increment x by random number
x(x() + Math.random());
```

This causes `x()` to run, kicking off an update of the dependency graph for no reason. It's also weird that the value of `x()` has to be exposed "outside" to accomplish the goal.

I'm going to add a `modify` method to reactive functions generated by `$R.state`:

```javascript
var x = $R.state(1);
//Increment x by random number
x.modify(function(v) { return v+ Math.random() });
```

**Comment by mattbaker** [comment]
Fixed in 1fa1457

**Comment by oliseviche** [comment]
Hello Matt.
I see that you have already change the behaviour for setting state values. According to my situation, when I first struggle upon it some time ago, I've made a simple change for stoping recalculation of dependent values when setting state value:

Only pure state object contains "val" member, so, in the "function $R" conctructor I've added some checks like:
```javascript
if (rf.hasOwnProperty("val")) {
    if (!arguments.length) {
        return v;
    }
}
```
to return state object value and not run calculation beneath. I know that such step "breaks" overall conductivity, but for me it was simple and elegant solution for a moment. And it still works.

**Comment by mattbaker** [comment]
Yup, which would work, but I didn't want to start adding special cases to the traversal and recalculation of the dependency graph. Slippery slope :)

**Comment by oliseviche** [comment]
Completely agreed.
I have another suggestion burning my mind, but I yhink that I will share it in another issue.

**Comment by mattbaker** [comment]
Please do!
